# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
    - package-ecosystem: "npm"
      # Use a wildcard to match all subdirectories in /basic
      directory: "/basic/*"
      schedule:
          interval: "daily"
      # Group all npm updates for each project together
      groups:
          npm-dependencies:
              patterns:
                  - "*"
    - package-ecosystem: "npm"
      # Use a wildcard to match all subdirectories in /expansions
      directory: "/expansions/*"
      schedule:
          interval: "daily"
      # Group all npm updates for each project together
      groups:
          npm-dependencies:
              patterns:
                  - "*"
