# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/basic/cra"
      schedule:
          interval: "daily"
    - package-ecosystem: "npm"
      directory: "/basic/cra-ts"
      schedule:
          interval: "daily"
    - package-ecosystem: "npm"
      directory: "/basic/cra_lint"
      schedule:
          interval: "daily"
    - package-ecosystem: "npm"
      directory: "/basic/vite"
      schedule:
          interval: "daily"
    - package-ecosystem: "npm"
      directory: "/basic/vite-ts"
      schedule:
          interval: "daily"
    - package-ecosystem: "npm"
      directory: "/expansions/cra_full"
      schedule:
          interval: "daily"
    - package-ecosystem: "npm"
      directory: "/expansions/cra_redux"
      schedule:
          interval: "daily"
    - package-ecosystem: "npm"
      directory: "/expansions/cra-ts_redux"
      schedule:
          interval: "daily"
