# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
      groups:
          npm-dependencies:
              patterns:
                  - "*"
    - package-ecosystem: "npm"
      directory: "/vanilla"
      schedule:
          interval: "weekly"
      groups:
          npm-dependencies:
              patterns:
                  - "*"
    # ts templates
    - package-ecosystem: "npm"
      directory: "/ts/vanilla"
      schedule:
          interval: "weekly"
      groups:
          npm-dependencies:
              patterns:
                  - "*"
    - package-ecosystem: "npm"
      directory: "/ts/redux"
      schedule:
          interval: "weekly"
      groups:
          npm-dependencies:
              patterns:
                  - "*"
    # extended templates
    - package-ecosystem: "npm"
      directory: "/extended/full"
      schedule:
          interval: "weekly"
      groups:
          npm-dependencies:
              patterns:
                  - "*"
    - package-ecosystem: "npm"
      directory: "/extended/redux"
      schedule:
          interval: "weekly"
      groups:
          npm-dependencies:
              patterns:
                  - "*"
